---
title: "Step 11 - A Bayesian HM for multivariate Guassian data and MCAR prior - derivation of full conditionals and comments on computing"
description: "Previously we introduced the MCAR model and simulated data from it. Now we will focus on fitting a Bayesian MCAR model to multivariate areal data using MCMC. It will be a naive pedagogical approach."
author:
  - name: Matthew Shisler
    affiliation: North Carloina State University - Department of Statistics
    affiliation-url: https://statistics.sciences.ncsu.edu/ 
date: "3/7/2023"
categories: [Bayesian, MCMC, Spatial, MCAR] # self-defined categories
draft: false 
format:
  html: 
    code-fold: true
execute: 
  cache: false
  freeze: false
---


```{r}
#| label: load-packages
#| output: false
#| code-summary: "Code: Load the packages"

library(tidyverse)
library(igraph)
library(viridis)
```

## Intro

In this post we will derive full conditionals for a Bayesian hierarchical model with an MCAR prior specified in the second stage. For simplicity, we will consider the case common spatial strength parameter $\rho$.

Let $\mathcal{D}$ be a spatial domain partitioned into $n$ areal units indexed by $i$. Following the notation of Step 3 (link), let $\boldsymbol\delta_i$ be a multivariate ($p \times 1$) response vector with conditional expectation
$$
\text{E}(\boldsymbol\delta_i \,|\,\boldsymbol\phi_i)  = \boldsymbol{\mathcal{Z}}_i \boldsymbol\beta + \boldsymbol\phi_i
$$
and covariance
$$
\text{Cov}(\boldsymbol\delta_i \,|\, \boldsymbol\phi_i) = \text{Cov}(\boldsymbol\epsilon_i) = \boldsymbol\Omega
$$

$$
\boldsymbol\delta_i = \boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i + \boldsymbol\epsilon_i
$$
where $\boldsymbol\epsilon_i \sim \text{N}\left(\boldsymbol 0, \boldsymbol\Omega\right)$ is a random noise vector.

We can specify the model with conditional priors on $\boldsymbol\phi{i}$

$$
\begin{align*}
\boldsymbol\delta_i &\sim \text{Normal}_{p}\left(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i, \,  \boldsymbol\Omega\right)\\
\boldsymbol\beta &\sim \text{Normal}_{qp}(\boldsymbol\mu, \, \boldsymbol\Gamma)\\
\boldsymbol\phi_i|\boldsymbol\phi_{j\ne i},\boldsymbol\Lambda &\sim \text{Normal}_p\left(\rho\sum_{i \sim j}\mathbf{B}_{ij}\boldsymbol\phi_j, \, w^{-1}_{i+}\boldsymbol\Lambda\right)\\
\omega_{kk} &\sim \text{InvGamm}(a_k, \, b_k) \quad \text{OR} \quad \boldsymbol\Omega \sim \text{InvWish}(\psi,\mathbf{G})\\
\boldsymbol\Lambda &\sim \text{InvWish}(\nu, \mathbf{R})\\
\rho &\sim \text{Unif}(0, \,1)
\end{align*}
$$

Or we can write the model in another way, with the joint distribution for $\boldsymbol\phi'$, the vector formed by stacking $\boldsymbol\phi_i$, $i = 1,\dots,n$.

$$
\begin{align*}
\boldsymbol\delta_i &\sim \text{Normal}_p\left(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i, \;  \boldsymbol\Omega\right)\\
\boldsymbol\beta &\sim \text{Normal}_{qp}\left(\boldsymbol\mu, \boldsymbol\Gamma\right)\\
\boldsymbol\phi' &\sim \text{Normal}_{np}\left(\boldsymbol 0, (\mathbf{D-\rho\mathbf{W}})^{-1} \otimes \boldsymbol\Lambda\right)\\
\omega_{kk} &\sim \text{InvGamm}(a_k, b_k) \quad \text{OR} \quad \boldsymbol\Omega \sim \text{InvWish}(\psi,\mathbf{G})\\
\boldsymbol\Lambda &\sim \text{InvWish}(\nu, \mathbf{R})\\
\rho &\sim \text{Unif}(0,1)
\end{align*}
$$

In this specification we take elements of $\boldsymbol\delta_i$ to be conditionally independent (i.e. $\boldsymbol\Omega$ is a diagonal matrix) which in general need not be the case.

## FC for Fixed effects - $\boldsymbol\beta$

Start with the full conditional for $\boldsymbol\beta$.
$$
\begin{align*}
p(\boldsymbol\beta \,|\, \text{rest}) &\propto p(\{\boldsymbol\delta_i\}, \boldsymbol\phi', \boldsymbol\beta, \boldsymbol\Omega, \boldsymbol\Lambda, \rho)\\
&\propto p(\{\boldsymbol\delta_i\} \,|\, \boldsymbol\beta, \boldsymbol\phi', \boldsymbol\Omega)p(\boldsymbol\beta)\\
&= \left[\prod_{i=1}^n p(\boldsymbol\delta_i \,|\, \boldsymbol\beta,\boldsymbol\phi_i,\boldsymbol\Omega)\right]p(\boldsymbol\beta)\\
&\propto \exp\left\{-\frac{1}{2}\sum_{i=1}^n\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]^T\boldsymbol\Omega^{-1}\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]\right\}\\
&\quad \, \times \exp\left\{-\frac{1}{2}\left[\boldsymbol\beta-\boldsymbol\mu\right]^T\boldsymbol\Gamma^{-1}\left[\boldsymbol\beta-\boldsymbol\mu\right]\right\}\\
&\propto \exp\left\{-\frac{1}{2}\left[\boldsymbol\beta^T\left(\sum_{i=1}^n\boldsymbol{\mathcal{Z}}_i^T\boldsymbol\Omega^{-1}\boldsymbol{\mathcal{Z}}_i\right)\boldsymbol\beta - 2\left(\sum_{i=1}^n(\boldsymbol\delta_i-\boldsymbol\phi_i)^T\boldsymbol\Omega^{-1}\boldsymbol{\mathcal{Z}}_i\right)\boldsymbol\beta\right]\right\}\\
&\quad \, \times \exp\left\{-\frac{1}{2}\left[\boldsymbol\beta^T\boldsymbol\Gamma^{-1}\boldsymbol\beta - 2\boldsymbol\mu^T\boldsymbol\Gamma^{-1}\boldsymbol\beta\right]\right\}\\
&\propto \exp\left\{-\frac{1}{2}\left[\boldsymbol\beta^T\left(\sum_{i=1}^n\boldsymbol{\mathcal{Z}}_i^T\boldsymbol\Omega^{-1}\boldsymbol{\mathcal{Z}}_i + \boldsymbol\Gamma^{-1}\right)\boldsymbol\beta - 2\left(\sum_{i=1}^n(\boldsymbol\delta_i-\boldsymbol\phi_i)^T\boldsymbol\Omega^{-1}\boldsymbol{\mathcal{Z}}_i + \boldsymbol\mu^T\boldsymbol\Gamma^{-1}\right)\boldsymbol\beta\right]\right\}
\end{align*}
$$
Thus,
$$
\begin{align*}
\boldsymbol\beta\,|\,\text{rest} &\sim \text{Normal}_{qp}(\mathbf{V}_\beta^{-1}\mathbf{M}_\beta, \mathbf{V}_\beta^{-1})\\
\mathbf{V}_\beta &= \sum_{i=1}^n\boldsymbol{\mathcal{Z}}^T_i\mathbf{\Omega}^{-1}\boldsymbol{\mathcal{Z}}_i + \mathbf{\Gamma}^{-1}\\
\mathbf{M}_\beta &= \sum_{i=1}^n\boldsymbol{\mathcal{Z}}^T_i\mathbf{\Omega}^{-1}(\boldsymbol\delta_i-\boldsymbol\phi_i) + \mathbf{\Gamma}^{-1}\boldsymbol\mu
\end{align*}
$$

## FC for Spatial Random Vector - $\boldsymbol\phi_i$ or $\boldsymbol\phi'$

Next we must determine the full conditional distribution for the spatial random vector. There are two approaches here, we could either derive full conditionals for $\boldsymbol\phi_i$ and draw samples in $n$ sub-blocks of parameters, or we could derive the full conditional for $\boldsymbol\phi'$ and update all $\boldsymbol\phi_i$ in a single block. It is hard to say which would be computationally preferable. The latter seems more interesting, though, so let's try to tackle that first, then derive the full conditionals for $\boldsymbol\phi_i$.

### Joint FC approach - $\boldsymbol\phi'$

The trickiness of updating $\boldsymbol\phi'$ as a single block is due to our model specification for $\boldsymbol\delta_i$. The likelihood for $\boldsymbol\delta_i$ is not compatible with the prior on $\boldsymbol\phi'$ because the spatial term in the former is specified in terms of $p \times 1$ vectors while in the latter spatial term is a $np \times 1$ vector.

We could either construct the joint distribution of the $\boldsymbol\delta_i$ vectors or we could try to write $\boldsymbol\phi_i$ in terms of $\boldsymbol\phi'$ and substitute into the corresponding $\boldsymbol\delta_i$ distributions. 

Let,
$$
\boldsymbol\Delta = 
\begin{pmatrix}
\delta_{11} & \dots & \delta_{1p}\\
\delta_{21} & \dots & \delta_{2p}\\
\vdots & \vdots & \vdots\\
\delta_{n1} & \dots & \delta_{np}\\
\end{pmatrix} =
\begin{pmatrix}
\boldsymbol\delta_1^T\\
\boldsymbol\delta_2^T\\
\vdots\\
\boldsymbol\delta_n^T\\
\end{pmatrix}
$$

Then define $\boldsymbol\delta' = \text{vec}(\boldsymbol\Delta^T)$. Since $\boldsymbol\delta_i$ are conditionally independent, the joint distribution for $\boldsymbol\delta'$ is

$$
\boldsymbol\delta' \sim \text{Normal}_{np} 
\left(
\begin{pmatrix}
\boldsymbol{\mathcal{Z}}_1\boldsymbol\beta\\
\boldsymbol{\mathcal{Z}}_2\boldsymbol\beta\\
\vdots \\
\boldsymbol{\mathcal{Z}}_n\boldsymbol\beta\\
\end{pmatrix} + \boldsymbol\phi', \;
\mathbf{I}_n \otimes \boldsymbol\Omega
\right)
$$
Again, the purpose of constructing the joint distribution in this way was to ensure the mean is in terms of $\boldsymbol\phi'$. But now the fixed effects term is a bit awkward. Let's avoid that temporarily by letting
$$
\mathbf{A} = 
\begin{pmatrix}
\boldsymbol{\mathcal{Z}}_1\boldsymbol\beta\\
\boldsymbol{\mathcal{Z}}_2\boldsymbol\beta\\
\vdots \\
\boldsymbol{\mathcal{Z}}_n\boldsymbol\beta\\
\end{pmatrix}.
$$

Then if we proceed in deriving the full conditional for $\boldsymbol\phi'$, we will have

$$
\begin{align*}
p(\boldsymbol\phi' \,|\, \text{rest}) &\propto p(\boldsymbol\delta', \boldsymbol\phi', \boldsymbol\beta, \boldsymbol\Omega, \boldsymbol\Lambda, \rho)\\
&\propto p(\{\boldsymbol\delta' \,|\, \boldsymbol\beta, \boldsymbol\phi', \boldsymbol\Omega)p(\boldsymbol\phi')\\
&\propto \exp\left\{-\frac{1}{2}\left[\boldsymbol\delta'-(\mathbf{A} + \boldsymbol\phi')\right]^T\left(\mathbf{I}_n \otimes \boldsymbol\Omega\right)^{-1}\left[\boldsymbol\delta_i-(\mathbf{A} + \boldsymbol\phi')\right]\right\}\\
&\quad \, \times \exp\left\{-\frac{1}{2}(\boldsymbol\phi')^T\left((\mathbf{D-\rho\mathbf{W}}) \otimes \boldsymbol\Lambda^{-1}\right)\boldsymbol\phi'\right\}\\
&\propto \exp\left\{-\frac{1}{2}\left[(\boldsymbol\phi')^T\left(\mathbf{I}_n \otimes \boldsymbol\Omega\right)^{-1}\boldsymbol\phi' - 2\left((\boldsymbol\delta'-\mathbf{A})^T\left(\mathbf{I}_n \otimes \boldsymbol\Omega\right)^{-1}\right)\boldsymbol\phi'\right]\right\}\\
&\quad \, \times \exp\left\{-\frac{1}{2}(\boldsymbol\phi')^T\left((\mathbf{D-\rho\mathbf{W}}) \otimes \boldsymbol\Lambda^{-1}\right)\boldsymbol\phi'\right\}\\
&\propto \exp\left\{-\frac{1}{2}\left[(\boldsymbol\phi')^T\left(\left(\mathbf{I}_n \otimes \boldsymbol\Omega\right)^{-1} + \left((\mathbf{D-\rho\mathbf{W}}) \otimes \boldsymbol\Lambda^{-1}\right)\right)\boldsymbol\phi' - 2\left((\boldsymbol\delta'-\mathbf{A})^T\left(\mathbf{I}_n \otimes \boldsymbol\Omega\right)^{-1}\right)\boldsymbol\phi'\right]\right\}
\end{align*}
$$
Thus,

$$
\begin{align*}
\boldsymbol\phi'\,|\,\text{rest} &\sim \text{Normal}_{np}(\mathbf{V}_{\phi'}^{-1}\mathbf{M}_{\phi'}, \mathbf{V}_{\phi'}^{-1})\\
\mathbf{V}_{\phi'} &= \left(\mathbf{I}_n \otimes \boldsymbol\Omega\right)^{-1} + \left((\mathbf{D-\rho\mathbf{W}}) \otimes \boldsymbol\Lambda^{-1}\right)\\
\mathbf{M}_{\phi'} &= \left(\mathbf{I}_n \otimes \boldsymbol\Omega\right)^{-1}(\boldsymbol\delta'-\mathbf{A})
\end{align*}
$$

This full conditional looks to be pretty clean, though we will need to consider efficient ways to compute $\mathbf{A}$. Before moving on, let's explore an alternative derivation for the full conditional of $\boldsymbol\phi'$.

If we instead wrote $\boldsymbol\phi_i$ in terms of $\boldsymbol\phi'$ when describing the distribution of $\boldsymbol\delta_i$? Consider the way in which one "extracts" a sub-vector of elements from a vector. We know there exists a $p \times np$ matrix $\mathbf{U}_i$ which will "extract" the $p \times 1$ dimension $\boldsymbol\phi_i$ vector from the $np \times 1$ dimenion $\boldsymbol\phi'$ vector. This $\mathbf{U}_i$ matrix will have all elements equal to $0$ except for $p$ columns forming a $p \times p$ identity matrix. The position of this $p \times p$ identity matrix in $\mathbf{U}_i$ determines which $\boldsymbol\phi_i$ to "extract" from $\boldsymbol\phi'$. In order to extract $\boldsymbol\phi_i$, then the $p \times p$ identity matrix must begin at column $(i-1)p + 1$ in $\mathbf{U}_i$

$$
\begin{align*}
\boldsymbol\phi_i &= 
\mathbf{U}_i\boldsymbol\phi'\\
&= \begin{pmatrix}
\boldsymbol{0}_p & \dots & \boldsymbol{0}_p & \mathbf{I}_p & \boldsymbol{0}_p & \dots & \boldsymbol{0}_p
\end{pmatrix}
\boldsymbol\phi'
\end{align*}
$$
where $\boldsymbol 0_p$ is a $p \times p$ matrix of $0$'s. Now we can write

$$
\boldsymbol\delta_i \sim \text{Normal}_p\left(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \mathbf{U}_i\boldsymbol\phi', \;  \boldsymbol\Omega\right)
$$
which will facilitate the derivation of the full conditional for $\boldsymbol\phi'$.

$$
\begin{align*}
p(\boldsymbol\phi' \,|\, \text{rest}) &\propto p(\{\boldsymbol\delta_i\}, \boldsymbol\phi', \boldsymbol\beta, \boldsymbol\Omega, \boldsymbol\Lambda, \rho)\\
&\propto p(\{\boldsymbol\delta_i\} \,|\, \boldsymbol\beta, \boldsymbol\phi', \boldsymbol\Omega)p(\boldsymbol\phi')\\
&= \left[\prod_{i=1}^n p(\boldsymbol\delta_i \,|\, \boldsymbol\beta,\boldsymbol\phi',\boldsymbol\Omega)\right]p(\boldsymbol\phi')\\
&\propto \exp\left\{-\frac{1}{2}\sum_{i=1}^n\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \mathbf{U}_i\boldsymbol\phi')\right]^T\boldsymbol\Omega^{-1}\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \mathbf{U}_i\boldsymbol\phi')\right]\right\}\\
&\quad \, \times \exp\left\{-\frac{1}{2}(\boldsymbol\phi')^T\left((\mathbf{D-\rho\mathbf{W}}) \otimes \boldsymbol\Lambda^{-1}\right)\boldsymbol\phi'\right\}\\
&\propto \exp\left\{-\frac{1}{2}\left[(\boldsymbol\phi')^T\left(\sum_{i=1}^n\mathbf{U}_i^T\boldsymbol\Omega^{-1}\mathbf{U}_i\right)\boldsymbol\phi' - 2\left(\sum_{i=1}^n(\boldsymbol\delta_i-\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta)^T\boldsymbol\Omega^{-1}\mathbf{U}_i\right)\boldsymbol\phi'\right]\right\}\\
&\quad \, \times \exp\left\{-\frac{1}{2}(\boldsymbol\phi')^T\left((\mathbf{D-\rho\mathbf{W}}) \otimes \boldsymbol\Lambda^{-1}\right)\boldsymbol\phi'\right\}\\
&\propto \exp\left\{-\frac{1}{2}\left[(\boldsymbol\phi')^T\left(\sum_{i=1}^n\mathbf{U}_i^T\boldsymbol\Omega^{-1}\mathbf{U}_i + \left((\mathbf{D-\rho\mathbf{W}}) \otimes \boldsymbol\Lambda^{-1}\right)\right)\boldsymbol\phi' - 2\left(\sum_{i=1}^n(\boldsymbol\delta_i-\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta)^T\boldsymbol\Omega^{-1}\mathbf{U}_i\right)\boldsymbol\phi'\right]\right\}
\end{align*}
$$
Thus,
$$
\begin{align*}
\boldsymbol\phi'\,|\,\text{rest} &\sim \text{Normal}_{np}(\mathbf{V}_{\phi'}^{-1}\mathbf{M}_{\phi'}, \mathbf{V}_{\phi'}^{-1})\\
\mathbf{V}_{\phi'} &= \sum_{i=1}^n\mathbf{U}_i^T\boldsymbol\Omega^{-1}\mathbf{U}_i + \left((\mathbf{D-\rho\mathbf{W}}) \otimes \boldsymbol\Lambda^{-1}\right)\\
\mathbf{M}_{\phi'} &= \sum_{i=1}^n\mathbf{U}^T_i\mathbf{\Omega}^{-1}(\boldsymbol\delta_i-\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta)
\end{align*}
$$

These two full conditionals for $\boldsymbol\phi'$ are equivalent. To see this we need to apply an identity previously described in Step 3 during the discussion of the full conditional for $\boldsymbol\beta$. In Step 3, we considered an organization of the covariates $\mathbf{z}_i$, into a matrix $\mathbf{Z} = (\mathbf{z}_1^T, \dots,\mathbf{z}_N^T)^T$
$$
\begin{equation}
\tag{3}
\mathbf{Z} = 
\begin{bmatrix}
1 & z_{12} & \dots & z_{1q}\\
\vdots & & \vdots &\\
1 & z_{N2} & \dots & z_{Nq}
\end{bmatrix}
=
\begin{bmatrix}
\mathbf{z}_1^T\\
\vdots\\
\mathbf{z}_N^T\\
\end{bmatrix}.
\end{equation}
$$
Notice, $\boldsymbol{\mathcal{Z}}_i = \mathbf{z}^T_i \otimes \mathbf{I}_p$. Then the following relate the sums to Kronecker products, (make this more general?)

$$
\begin{equation}
\tag{4}
\sum_{i=1}^N\boldsymbol{\mathcal{Z}}^T_i\boldsymbol\Omega^{-1}\boldsymbol{\mathcal{Z}}_i = \mathbf{Z}^T\mathbf{Z} \otimes \boldsymbol\Omega^{-1}
\end{equation}
$$

$$
\begin{equation}
\tag{5}
\sum_{i=1}^N\boldsymbol{\mathcal{Z}}^T_i\mathbf{\Omega}^{-1}\boldsymbol\delta_i =  \text{vec}(\Omega^{-1}\boldsymbol\Delta\mathbf{Z}) = (\mathbf{Z}^T \otimes \, \boldsymbol\Omega^{-1})\text{vec}(\boldsymbol\Delta).
\end{equation}
$$
In the case of the full conditional for $\boldsymbol\phi'$, we have $\mathbf{U}_i = \mathbf{u}^T_i \otimes I_n$ where $\mathbf{u}_i$ is an elementary vector with $1$ in position $i$ and $0$ elsewhere. Stacking rows of $\mathbf{u}_i^T$ into a matrix constructs the identity matrix $\mathbf{I}_n$. So, substituting $\mathbf{U}_i$ for $\boldsymbol{\mathcal{Z}}_i$ and $\mathbf{I}_n$ for $\mathbf{Z}$ yields

$$
\begin{equation}
\tag{4}
\sum_{i=1}^N\mathbf{U}_i^T\boldsymbol\Omega^{-1}\mathbf{U}_i = \mathbf{I}_n^T\mathbf{I}_n \otimes \boldsymbol\Omega^{-1} = \mathbf{I}_n \otimes \boldsymbol\Omega^{-1}
\end{equation}
$$

Also, substituting $\mathbf{U}_i$ for $\boldsymbol{\mathcal{Z}}_i$ and $\boldsymbol\delta_i - \boldsymbol{\mathcal{Z}}_i\boldsymbol\beta$ for $\boldsymbol\delta_i$ yields
$$
\begin{equation}
\tag{5}
\sum_{i=1}^N\mathbf{U}_i\mathbf{\Omega}^{-1}(\boldsymbol\delta_i - \boldsymbol{\mathcal{Z}}_i\boldsymbol\beta) =  \text{vec}(\Omega^{-1}\boldsymbol\Delta\mathbf{I}_n) = (\mathbf{I}_n^T \otimes \, \boldsymbol\Omega^{-1})(\boldsymbol\delta'-\mathbf{A}).
\end{equation}
$$
This shows that the two approaches to deriving the full conditional for $\boldsymbol\phi'$ yield the same results.

Returning to $\mathbf{A}$, which is necessary to compute in the block full conditional for $\boldsymbol\phi'$. We recognize that

$$
\begin{align*}
\mathbf{A} &= 
\begin{pmatrix}
\boldsymbol{\mathcal{Z}}_1\boldsymbol\beta\\
\vdots \\
\boldsymbol{\mathcal{Z}}_n\boldsymbol\beta\\
\end{pmatrix}\\
&= 
\begin{pmatrix}
\mathbf{B}\mathbf{z_1}\\
\vdots \\
\mathbf{B}\mathbf{z_n}\\
\end{pmatrix}\\
&= \text{vec}(\mathbf{B}\mathbf{Z^T})
\end{align*}
$$
So we can substitute,
$$
(\boldsymbol\delta' - \mathbf{A}) = \text{vec}(\boldsymbol\Delta-\mathbf{B}\mathbf{Z}^T)
$$
in the full conditional for $\boldsymbol\phi'$.

### Marginal (site-by-site) FC approach - $\boldsymbol\phi_i$

We might desire to sample full conditionals for $\boldsymbol\phi_i$ rather than the full joint distribution for $\boldsymbol\phi'$. 

$$
\begin{align*}
p(\boldsymbol\phi_i \,|\, \text{rest})
&\propto 
p(\{\boldsymbol\delta_i\}, \{\boldsymbol\phi_i\}, \boldsymbol\beta, \boldsymbol\Omega, \boldsymbol\Lambda, \rho)\\
&\propto 
p(\boldsymbol\delta_i \,|\, \boldsymbol\phi_i, \boldsymbol\beta, \boldsymbol\Omega)p(\boldsymbol\phi_i \,|\, \boldsymbol\Lambda, \rho)\\
&\propto 
\exp\left\{-\frac{1}{2}\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]^T\boldsymbol\Omega^{-1}\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]\right\}\\
&\quad \, \times 
\exp\left\{-\frac{w_{i+}}{2}\left(\boldsymbol\phi_i - \rho\sum_{j \in \mathcal{N}_i}\mathbf{B}_{ij}\boldsymbol\phi_j\right)^T\boldsymbol\Lambda^{-1}\left(\boldsymbol\phi_i - \rho\sum_{j \in \mathcal{N}_i}\mathbf{B}_{ij}\boldsymbol\phi_j\right)\right\}\\
&\propto 
\exp\left\{-\frac{1}{2}\left[(\boldsymbol\phi_i)^T\boldsymbol\Omega^{-1}\boldsymbol\phi_i - 2\left(\boldsymbol\delta_i^T -\boldsymbol\beta^T\boldsymbol{\mathcal{Z}}^T_i\right)\boldsymbol\Omega^{-1}\boldsymbol\phi_i\right]\right\}\\
&\quad \, \times 
\exp\left\{-\frac{1}{2}\left[(\boldsymbol\phi_i)^Tw_{i+}\boldsymbol\Lambda^{-1}\boldsymbol\phi_i - 2\rho w_{i+}\left(\sum_{j \in \mathcal{N}_i}\boldsymbol\phi_j^T\mathbf{B}_{ij}^T\right)\boldsymbol\Lambda^{-1}\boldsymbol\phi_i\right]\right\}\\
&=
\exp\left\{-\frac{1}{2}\left[(\boldsymbol\phi_i)^T\left(\boldsymbol\Omega^{-1} + w_{i+}\boldsymbol\Lambda^{-1}\right)\boldsymbol\phi_i - 2\left[\left(\boldsymbol\delta_i^T -\boldsymbol\beta^T\boldsymbol{\mathcal{Z}}^T_i\right)\boldsymbol\Omega^{-1} + \rho w_{i+}\left(\sum_{j \in \mathcal{N}_i}\boldsymbol\phi_j^T\mathbf{B}_{ij}^T\right)\boldsymbol\Lambda^{-1}\right]\boldsymbol\phi_i\right]\right\}\\
\end{align*}
$$

Thus,

$$
\begin{align*}
\boldsymbol\phi_i\,|\,\text{rest} &\sim \text{Normal}_{p}(\mathbf{V}_{\phi_i}^{-1}\mathbf{M}_{\phi_i}, \mathbf{V}_{\phi_i}^{-1})\\
\mathbf{V}_{\phi_i} &= \boldsymbol\Omega^{-1} + w_{i+}\boldsymbol\Lambda^{-1}\\
\mathbf{M}_{\phi_i} &= \boldsymbol\Omega^{-1}\left(\boldsymbol\delta_i-\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta\right) + \rho w_{i+}\boldsymbol\Lambda^{-1}\sum_{j \in \mathcal{N}_i}\mathbf{B}_{ij}\boldsymbol\phi_j
\end{align*}
$$
taking $\mathbf{B}_{ij} = \frac{w_{ij}}{w_{i+}}\mathbf{I}_p$, we will have $\mathbf{M}_{\phi_i} = \boldsymbol\Omega^{-1}\left(\boldsymbol\delta_i-\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta\right) + \rho \boldsymbol\Lambda^{-1}\sum_{j \in \mathcal{N}_i}w_{ij}\boldsymbol\phi_j$.

## FC for Covariance of the Spatial Random Vector - $\boldsymbol\Lambda$

### Using joint distribution for $\boldsymbol\phi'$

$$
\begin{align*}
p(\boldsymbol\Lambda \,|\, \text{rest}) &\propto p(\{\boldsymbol\delta_i\}, \boldsymbol\phi', \boldsymbol\beta, \boldsymbol\Omega, \boldsymbol\Lambda, \rho)\\
&\propto 
p(\boldsymbol\phi'|\boldsymbol\Lambda,\rho)p(\boldsymbol\Lambda)\\
&\propto 
\big|(\mathbf{D} - \rho\mathbf{W})^{-1} \otimes \boldsymbol\Lambda\big|^{-1/2} \exp\left\{-\frac{1}{2}\left(\boldsymbol\phi'\right)^T\left((\mathbf{D} - \rho\mathbf{W})^{-1}\otimes\boldsymbol\Lambda\right)^{-1}\boldsymbol\phi'\right\}\\
&\quad \; 
\times \big|\boldsymbol\Lambda\big|^{-(\nu + p + 1)/2} \exp\left\{-\frac{1}{2}\text{Tr}(\boldsymbol\Lambda^{-1}\mathbf{R})\right\}\\
&\propto 
\big|\boldsymbol\Lambda\big|^{-p/2} \exp\left\{-\frac{1}{2}\text{Tr}\left(\left(\boldsymbol\phi'\right)^T\left((\mathbf{D} - \rho\mathbf{W})\otimes\boldsymbol\Lambda^{-1}\right)\boldsymbol\phi'\right)\right\}\\
&\quad \; 
\times \big|\boldsymbol\Lambda\big|^{-(\nu + p + 1)/2} \exp\left\{-\frac{1}{2}\text{Tr}(\boldsymbol\Lambda^{-1}\mathbf{R})\right\}\\
&\propto 
\big|\boldsymbol\Lambda\big|^{-p/2} \exp\left\{-\frac{1}{2}\text{Tr}\left(\boldsymbol\Lambda^{-1} \boldsymbol\Phi^T(\mathbf{D}-\rho\mathbf{W})\boldsymbol\Phi\right)\right\}\\
&\quad \; 
\times \big|\boldsymbol\Lambda\big|^{-(\nu + p + 1)/2} \exp\left\{-\frac{1}{2}\text{Tr}(\boldsymbol\Lambda^{-1}\mathbf{R})\right\}\\
&= \big|\boldsymbol\Lambda\big|^{-(p +\nu + p + 1)/2} \exp\left\{-\frac{1}{2}\text{Tr}(\boldsymbol\Lambda^{-1}\left(\mathbf{R} + \boldsymbol\Phi^T(\mathbf{D}-\rho\mathbf{W})\boldsymbol\Phi \right)\right\}
\end{align*}
$$
Thus,
$$
\begin{align*}
\boldsymbol\Lambda \,|\, \text{rest} &\sim \text{InvWish}\left(p + \nu, \mathbf{R}+\mathbf{S}\right)\\
p &= \text{dim}(\boldsymbol\phi_i)\\
\mathbf{S} &= \boldsymbol\Phi^T(\mathbf{D}-\rho\mathbf{W})\boldsymbol\Phi
\end{align*}
$$

::: {.callout-note}
I believe I've completed this derivation. The key trick is found in *Aspects of Multivariate Statistical Theory* by Robb J. Muirhead on page 76, Lemma 2.2.3. Interestingly it is not immediately obvious that it agrees with the following derivation using Brook's Lemma. Perhaps that is something worth checking. The route using Brook's Lemma was tedious. I would not be surprised if I made some errors there.
:::

### Using conditional distributions for $\boldsymbol\phi_i$ and Brook's Lemma

An alternative path, let's attempt to derive the full conditional for $\boldsymbol\Lambda$ using the conditional distributions for $\boldsymbol\phi_i$.

$$
\begin{align*}
p(\boldsymbol\Lambda \,|\, \text{rest}) &\propto p(\{\boldsymbol\delta_i\}, \{\boldsymbol\phi_i\}, \boldsymbol\beta, \boldsymbol\Omega, \boldsymbol\Lambda, \rho)\\
&\propto p(\boldsymbol\phi'|\boldsymbol\Lambda,\rho)p(\boldsymbol\Lambda)\\
&= \frac{p(\boldsymbol\phi_1 \,|\, \{\boldsymbol\phi_{i}\}_{i=2}^n)}{p(\boldsymbol\phi_{1,0} \,|\, \{\boldsymbol\phi_{i}\}_{i=2}^n)} \frac{p(\boldsymbol\phi_2 \,|\, \{\boldsymbol\phi_{j,0}\}_{j=1}^1,\{\boldsymbol\phi_{i}\}_{i=3}^n)}{p(\boldsymbol\phi_{2,0} \,|\, \{\boldsymbol\phi_{j,0}\}_{j=1}^1,\{\boldsymbol\phi_{i}\}_{i=3}^n)}
\times \\
&\quad \quad \vdots \\
&\quad \;\times\frac{p(\boldsymbol\phi_k \,|\, \{\boldsymbol\phi_{j,0}\}_{j=1}^{k-1},\{\boldsymbol\phi_{i}\}_{i={k+1}}^n)}{p(\boldsymbol\phi_{k,0} \,|\, \{\boldsymbol\phi_{j,0}\}_{j=1}^{k-1},\{\boldsymbol\phi_{i}\}_{i={k+1}}^n)} \times\\
&\quad \quad \vdots \\
&\quad \;\times\frac{p(\boldsymbol\phi_n \,| \, 
\{\boldsymbol\phi_{j,0}\}_{j=1}^{n-1})}{p(\boldsymbol\phi_{n,0} \,| \, 
\{\boldsymbol\phi_{j,0}\}_{j=1}^{n-1})} p(\boldsymbol\phi' = \boldsymbol\phi'_0 \,|\, \boldsymbol\Lambda,\rho)p(\boldsymbol\Lambda)
\end{align*}
$$
where the last line follows by application of Brook's Lemma to $p(\boldsymbol\phi'|\boldsymbol\Lambda,\rho)$. We've dropped $\boldsymbol\Lambda$ and $\rho$ from conditioning notation in the resulting product of ratios, but the conditioning is very much still present. We choose $\boldsymbol\phi'_0 = \boldsymbol{0}$ for the fixed point in the support of $\boldsymbol\phi'$. This will simplify things later and allow us to avoid the situation we ran into ealier.

::: {.callout-note}
Could I have derived the full conditionals incorrectly for the univariate case? I think I just used the product of the conditionals there and not Brook's Lemma. . . this might explain why my MCMC had issues with convergence. I should go back and check.
:::

We have a particularly tedious product of ratios. Let's focus on the $k$th term first, then consider the entire product to understand the form of the full conditional for $\boldsymbol\Lambda$. Let
$$
\mathbf{m}_k = \rho\sum_{\substack{j \in \mathcal{N}_k \\ j \, > \, k}}\mathbf{B}_{kj}\boldsymbol\phi_j
$$
Note that at the $k$th term we are considering the density as a function of some non-zero conditioned variates. The $\boldsymbol\phi_j$ for $j < k$ have been set to $\mathbf{0}$. This may affect the sum in the conditional mean, so we restrict the sum to terms that are non-zero, that is $\boldsymbol\phi_j$ where $j \in \mathcal{N}_k$ and $j > k$.

Then the $k$th term,
$$
\begin{align*}
\frac{p(\boldsymbol\phi_k \,|\, \{\boldsymbol\phi_{j,0}\}_{j=1}^{k-1},\{\boldsymbol\phi_{i}\}_{i={k+1}}^n)}{p(\boldsymbol\phi_{k,0} \,|\, \{\boldsymbol\phi_{j,0}\}_{j=1}^{k-1},\{\boldsymbol\phi_{i}\}_{i={k+1}}^n)}
&= 
\frac{\exp\left\{-\frac{w_{k+}}{2}\left(\boldsymbol\phi_k-\mathbf{m}_k\right)^T\boldsymbol\Lambda^{-1}\left(\boldsymbol\phi_k-\mathbf{m}_k\right)\right\}}{\exp\left\{-\frac{w_{k+}}{2}\left(\boldsymbol{0}-\mathbf{m}_k\right)^T\boldsymbol\Lambda^{-1}\left(\boldsymbol{0}-\mathbf{m}_k\right)\right\}}\\
&=
\exp\left\{-\frac{w_{k+}}{2}\left(\boldsymbol\phi_k-\mathbf{m}_k\right)^T\boldsymbol\Lambda^{-1}\left(\boldsymbol\phi_k-\mathbf{m}_k\right) + \frac{w_{k+}}{2}\mathbf{m}_k^T\boldsymbol\Lambda^{-1}\mathbf{m}_k\right\}\\
&=
\exp\left\{-\frac{w_{k+}}{2}\left[\left(\boldsymbol\phi_k-\mathbf{m}_k\right)^T\boldsymbol\Lambda^{-1}\left(\boldsymbol\phi_k-\mathbf{m}_k\right) -\mathbf{m}_k^T\boldsymbol\Lambda^{-1}\mathbf{m}_k\right]\right\}\\
&=
\exp\left\{-\frac{w_{k+}}{2}\left[\boldsymbol\phi^T_k\boldsymbol\Lambda^{-1}\boldsymbol\phi_k - 2\mathbf{m}_k^T\boldsymbol\Lambda^{-1}\boldsymbol\phi^T_k\right]\right\}\\
&=
\exp\left\{-\frac{w_{k+}}{2}\text{Tr}\left[\boldsymbol\phi^T_k\boldsymbol\Lambda^{-1}\boldsymbol\phi_k - 2\mathbf{m}_k^T\boldsymbol\Lambda^{-1}\boldsymbol\phi_k\right]\right\}\\
&=
\exp\left\{-\frac{w_{k+}}{2}\left(\text{Tr}\left[\boldsymbol\phi^T_1\boldsymbol\Lambda^{-1}\boldsymbol\phi_k\right] - \text{Tr}\left[ 2\mathbf{m}_k^T\boldsymbol\Lambda^{-1}\boldsymbol\phi_k\right]\right)\right\}\\
&=
\exp\left\{-\frac{w_{k+}}{2}\left(\text{Tr}\left[\boldsymbol\Lambda^{-1}\boldsymbol\phi_k\boldsymbol\phi^T_k\right] - \text{Tr}\left[ 2\boldsymbol\Lambda^{-1}\boldsymbol\phi_k\mathbf{m}_k^T\right]\right)\right\}\\
&=
\exp\left\{-\frac{w_{k+}}{2}\text{Tr}\left[\boldsymbol\Lambda^{-1}\left(\boldsymbol\phi_k\boldsymbol\phi^T_k -  2\boldsymbol\phi_k\mathbf{m}_k^T\right)\right]\right\}\\
\end{align*}
$$

Then the entire product will be
$$
\begin{align*}
p(\boldsymbol\phi'|\boldsymbol\Lambda,\rho) 
&=
\left[\prod_{k=1}^n \frac{p(\boldsymbol\phi_k \,|\, \{\boldsymbol\phi_{j,0} = \mathbf{0}\}_{j=1}^{k-1},\{\boldsymbol\phi_{i}\}_{i={k+1}}^n, \boldsymbol\Lambda, \rho)}{p(\boldsymbol\phi_{k,0} = \mathbf{0} \,|\, \{\boldsymbol\phi_{j,0} = \mathbf{0}\}_{j=1}^{k-1},\{\boldsymbol\phi_{i}\}_{i={k+1}}^n, \boldsymbol\Lambda, \rho)}\right]p(\boldsymbol\phi' = \mathbf{0} \,|\, \boldsymbol\Lambda,\rho)\\
&=
\left[\prod_{k=1}^n \exp\left\{-\frac{w_{k+}}{2}\text{Tr}\left[\boldsymbol\Lambda^{-1}\left(\boldsymbol\phi_k\boldsymbol\phi^T_k -  2\boldsymbol\phi_k\mathbf{m}_k^T\right)\right]\right\}\right]p(\boldsymbol\phi' = \mathbf{0} \,|\, \boldsymbol\Lambda,\rho)\\
&=
\exp\left\{-\frac{1}{2}\sum_{k=1}^n\text{Tr}\left[\boldsymbol\Lambda^{-1}w_{k+}\left(\boldsymbol\phi_k\boldsymbol\phi^T_k -  2\boldsymbol\phi_k\mathbf{m}_k^T\right)\right]\right\}p(\boldsymbol\phi' = \mathbf{0} \,|\, \boldsymbol\Lambda,\rho)\\
&=
\exp\left\{-\frac{1}{2}\text{Tr}\left[\boldsymbol\Lambda^{-1} \sum_{k=1}^n \mathbf{S}_k\right]\right\} \times \big|(\mathbf{D} - \rho\mathbf{W})^{-1} \otimes \boldsymbol\Lambda\big|^{-1/2} \exp\left\{-\frac{1}{2}\left(\mathbf{0}\right)^T\left((\mathbf{D} - \rho\mathbf{W})^{-1}\otimes\boldsymbol\Lambda\right)^{-1}\mathbf{0}\right\}\\
&= \big|(\mathbf{D} - \rho\mathbf{W})^{-1} \otimes \boldsymbol\Lambda\big|^{-1/2}
\exp\left\{-\frac{1}{2}\text{Tr}\left[\boldsymbol\Lambda^{-1} \sum_{k=1}^n \mathbf{S}_k\right]\right\}
\end{align*}
$$

where $\mathbf{S}_k = w_{k+}\left(\boldsymbol\phi_k\boldsymbol\phi^T_k -  2\boldsymbol\phi_k\mathbf{m}_k^T\right)$.

Finally, the full conditional for $\boldsymbol\Lambda$ is
$$
\begin{align*}
p(\boldsymbol\Lambda \,|\, \text{rest}) &\propto p(\{\boldsymbol\delta_i\}, \{\boldsymbol\phi_i\}, \boldsymbol\beta, \boldsymbol\Omega, \boldsymbol\Lambda, \rho)\\
&\propto p(\boldsymbol\phi'|\boldsymbol\Lambda,\rho)p(\boldsymbol\Lambda)\\
&= 
\big|(\mathbf{D} - \rho\mathbf{W})^{-1} \otimes \boldsymbol\Lambda\big|^{-1/2}
\exp\left\{-\frac{1}{2}\text{Tr}\left[\boldsymbol\Lambda^{-1} \sum_{k=1}^n \mathbf{S}_k\right]\right\}\\
&\quad \;\times 
 \big|\boldsymbol\Lambda\big|^{-(\nu + p + 1)/2} \exp\left\{-\frac{1}{2}\text{Tr}(\boldsymbol\Lambda^{-1}\mathbf{R})\right\}\\
&\propto 
\big|\boldsymbol\Lambda\big|^{-p/2}
\exp\left\{-\frac{1}{2}\text{Tr}\left[\boldsymbol\Lambda^{-1} \sum_{k=1}^n \mathbf{S}_k\right]\right\}\\
&\quad \;\times 
\big|\boldsymbol\Lambda\big|^{-(\nu + p + 1)/2} \exp\left\{-\frac{1}{2}\text{Tr}\left[\boldsymbol\Lambda^{-1}\mathbf{R}\right]\right\}\\
&=
\big|\boldsymbol\Lambda\big|^{-(\nu + 2p + 1)/2} \exp\left\{-\frac{1}{2}\text{Tr}\left[\boldsymbol\Lambda^{-1}\left(\mathbf{R} + \sum_{k=1}^n \mathbf{S}_k\right)\right]\right\}\\
\end{align*}
$$
and we conclude $\boldsymbol\Lambda \,|\, \text{rest} \sim \text{InvWish}\left(p + \nu,\, \mathbf{R} + \sum_{k=1}^n \mathbf{S}_k\right)$

This full conditional seems reasonable, but computing $\sum_{k=1}^n \mathbf{S}_k$ may prove a bit tricky. Perhaps there are some simplifications to be made for this term in particular.

$$
\begin{align*}
\sum_{k=1}^n \mathbf{S}_k &= \sum_{k=1}^nw_{k+}\left(\boldsymbol\phi_k\boldsymbol\phi^T_k -  2\boldsymbol\phi_k\mathbf{m}_k^T\right)\\
&= \sum_{k=1}^nw_{k+}\boldsymbol\phi_k\boldsymbol\phi^T_k - \sum_{k=1}^nw_{k+}2\boldsymbol\phi_k\mathbf{m}_k^T\\
&= \sum_{k=1}^nw_{k+}\boldsymbol\phi_k\boldsymbol\phi^T_k - \sum_{k=1}^nw_{k+}2\boldsymbol\phi_k\rho\sum_{\substack{j \in \mathcal{N}_k \\ j \, > \, k}}\boldsymbol\phi_j^T\mathbf{B}^T_{kj}\\
&= \mathbf{D}\boldsymbol\Phi^T\boldsymbol\Phi - 2\rho\sum_{k=1}^nw_{k+}\boldsymbol\phi_k\sum_{\substack{j \in \mathcal{N}_k \\ j \, > \, k}}\boldsymbol\phi_j^T\mathbf{B}^T_{kj}\\
&= \mathbf{D}\boldsymbol\Phi^T\boldsymbol\Phi - 2\rho\sum_{k=1}^nw_{k+}\boldsymbol\phi_k\sum_{\substack{j \in \mathcal{N}_k \\ j \, > \, k}}\frac{w_{kj}}{w_{k+}}\boldsymbol\phi_j^T\mathbf{I}_p \quad \quad \text{set } \mathbf{B}_{kj} = \frac{w_{kj}}{w_{k+}}\mathbf{I}_p\\
&= \mathbf{D}\boldsymbol\Phi^T\boldsymbol\Phi - 2\rho\sum_{k=1}^n\boldsymbol\phi_k\sum_{\substack{j \in \mathcal{N}_k \\ j \, > \, k}}w_{kj}\boldsymbol\phi_j^T\\
&= \mathbf{D}\boldsymbol\Phi^T\boldsymbol\Phi - 2\rho\boldsymbol\Phi^T\mathbf{W}_{U}\boldsymbol\Phi\\
&= 
\end{align*}
$$
Where $\mathbf{W}_U$ is ab $n \times n$ upper triangular matrix constructed by zeroing out the lower triangle of $\mathbf{W}$. This has the affect of setting $\boldsymbol\phi_j = \boldsymbol 0$ for $j \le k$ which defines the sum $\sum_{\substack{j \in \mathcal{N}_k \\ j \, > \, k}}w_{kj}\boldsymbol\phi_j^T$.


It is important to note that $\boldsymbol\Phi$ is constructed with *rows* equal to $\boldsymbol\phi_k$ which results in flipping $\boldsymbol\Phi\boldsymbol\Phi^T$, what we would expect, to instead be $\boldsymbol\Phi^T\boldsymbol\Phi$.

::: {.callout-note}
This is suspiciously close to $(\mathbf{D}-\rho\mathbf{W})\boldsymbol\Phi^T\boldsymbol\Phi$. Perhaps $2\boldsymbol\Phi^T\mathbf{W}_U\boldsymbol\Phi = \boldsymbol\Phi^T\mathbf{W}\boldsymbol\Phi$? It would be nice, but actually I don't think this is true.
:::

## FC for $\boldsymbol\Omega$

Next, we will consider the full conditional for $\boldsymbol\Omega$ under two cases. Either $\boldsymbol\Omega$ is diagonal, i.e. $\boldsymbol\delta_i$ is independent conditional on $\boldsymbol\phi_i$, or $\boldsymbol\Omega$ is symmetric positive-definite matrix, i.e. no assumed structure.

### General $\boldsymbol\Omega$

We'll get right into it

$$
\begin{align*}
p(\boldsymbol\Omega \,|\, \text{rest}) 
&\propto 
p(\{\boldsymbol\delta_i\}, \{\boldsymbol\phi_i\}, \boldsymbol\beta,\boldsymbol\Omega, \boldsymbol\Lambda,\rho)\\
&\propto
\left[\prod_{i=1}^n p(\boldsymbol\delta_i \,|\, \boldsymbol\beta,\boldsymbol\phi_i,\boldsymbol\Omega)\right]p(\boldsymbol\Omega)\\
&\propto
|\boldsymbol\Omega|^{n/2}\exp\left\{-\frac{1}{2}\sum_{i=1}^n\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]^T\boldsymbol\Omega^{-1}\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]\right\}\\
&\quad \; \times |\boldsymbol\Omega|^{-(\xi + p + 1)/2}\exp\left\{-\frac{1}{2}\text{Tr}\left(\boldsymbol\Omega^{-1}\mathbf{G}\right)\right\}\\
&= |\boldsymbol\Omega|^{-(n + \xi + p + 1)/2}\exp\left\{-\frac{1}{2}\text{Tr}\left(\boldsymbol\Omega^{-1}(\mathbf{H} + \mathbf{G})\right)\right\}\\
\end{align*}
$$

where $\mathbf{H} = \sum_{i=1}^n\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]^T$

Thus,
$$
\begin{align*}
\boldsymbol\Omega \,|\, \text{rest} &\sim \text{InvWish}\left(n+\xi, \mathbf{H}+\mathbf{G}\right)\\
n &= \text{number of spatial locations}\\
\mathbf{H} &= \sum_{i=1}^n\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]\left[\boldsymbol\delta_i-(\boldsymbol{\mathcal{Z}}_i\boldsymbol\beta + \boldsymbol\phi_i)\right]^T
\end{align*}
$$

### Diagonal $\boldsymbol\Omega$

TODO

## Metropolis-Hastings Step for Spatial Stength parameter - $\rho$

TODO



