project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!render_ignore/"
  
website:
  title: "MS"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: learn.qmd
        text: Learn
      - href: notes.qmd
        text: Notes

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true


