project:
  type: website
  output-dir: docs
  
website:
  title: "MS"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: learn.qmd
        text: Learn

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true


